blank_issues_enabled: false
contact_links:
  - name: ğŸ’¡ Feature Request
    url: https://github.com/CHANGEME/discussions
    about: Suggest an idea for this project..
  - name: ğŸŸï¸ Support Ticket
    url: https://github.com/CHANGEME/discussions
    about: Talk to us if you need help..
